### ISSUE TITLE
Question about the Colored MNIST

### ISSUE THREAD

**Issue by TongZhangTHU** [facebookresearch/InvariantRiskMinimization#6]
Hi author,

Thanks for your wonderful work.  But I am confused  why "obtain the final label y by flipping ~y with probability 0.25". Without this, IRM may get no better than ERM?

**Comment by zdhNarsil** [comment]
You are right. The goal of label noise is just to make the *correlation between shape and label* to be lower than *correlation between color and label*, which makes ERM fails. Without label noise, ERM will be the optimal algorithm.
